Create new design for web, change mobile version and add PWA
Scheepsjongen/scheepsjongen.github.io pull request #2
Opened 2020-11-17 22:45 UTC by TanyaMelnichuk

2020-11-18 11:50 UTC, Olezha requested changes

2020-11-18 11:50 UTC, Olezha commented on manifest.json
> +  }
No newline at end of file

2020-11-18 11:50 UTC, Olezha commented on sw.js
> +const staticCacheName="static-cache-v0",dynamicCacheName="dynamic-cache-v0",staticAssets=["./","index.html"];async function checkCache(e){return await caches.match(e)||checkOnline(e)}async function c
Тут нужно сделать читаемый код и настроить кэширование

2020-11-18 11:50 UTC, Olezha commented on js/app.js
> +window.addEventListener("load",()=>{"serviceWorker"in navigator&&navigator.serviceWorker.register("./sw.js").then(e=>{console.log("Service worker successfully registered",e)}).catch(e=>{console.log("
`app.js` лежит в папке `js` и тут линк к `sw.js`, который в корне сайта. Стоит перепроверить правильно ли писать  `./sw.js`?

2020-11-19 20:45 UTC, TanyaMelnichuk commented on js/app.js
> +window.addEventListener("load",()=>{"serviceWorker"in navigator&&navigator.serviceWorker.register("./sw.js").then(e=>{console.log("Service worker successfully registered",e)}).catch(e=>{console.log("
Так правильно

2020-11-19 22:47 UTC, Olezha approved these changes

2020-11-19 22:48 UTC, merged